### ISSUE TITLE
Using ModelFormMixin (base class of UpdateView) without the 'fields' attribute is prohibited

### ISSUE THREAD

**Issue by andy2046** [Alem/django-bootstrap-crud-templates#14]
Please help

ImproperlyConfigured at /incident/inventory/update/1
Using ModelFormMixin (base class of UpdateView) without the 'fields' attribute is prohibited.

**Comment by scottx611x** [comment]
@andy2046 I believe I've addressed this issue in #15

**Comment by jameskandau** [comment]
You are not supplying the fields after model

eg 
model = Post
fields = '__all__'  (add the fields you want to create if not all)

**Comment by OfranSassi** [comment]
In my case I did put fields = '__all__' and still the same error

**Comment by DmytroLitvinov** [comment]
@OfranSassi, you need to write something like `fields = '__all__'`

**Comment by mateojoms** [comment]
supposed to be something like:
fields=="__all__"

**Comment by yutounun** [comment]
@DmytroLitvinov in my case, I put `fields = '__all__'`, but still same error exists

**Comment by Mar3eczek17** [comment]
Also I too.... @yutounun @DmytroLitvinov in my case works if:
in folder with views.py in file urls.py:

    path('category/<int:pk>/update/',
         UpdateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-update'),
